// Keeps the icon font, its codepoints and the extension manifest in agreement.
//
// The standard workflow here is to cretate an SVG in assets/icons and run `just icons`.
//
// The glyph is given a codepoint which is pinned in .fantasticonrc.json so, and
// adds the contributes.icons entry to package.json. Support renames or deletes
// of the SVG as well.

import { readdirSync, readFileSync, writeFileSync } from "fs";

const RC = ".fantasticonrc.json";
const MANIFEST = "package.json";
const ICONS_TS = "src/icons.ts";
const GENERATED = "assets/mindful-stage.json";
const ICONS = "assets/icons";

const write = (file, value) =>
  writeFileSync(file, `${JSON.stringify(value, null, 2)}\n`);

const names = readdirSync(ICONS)
  .filter((file) => file.endsWith(".svg"))
  .map((file) => file.slice(0, -".svg".length))
  .sort();

const generated = JSON.parse(readFileSync(GENERATED, "utf8"));
const rc = JSON.parse(readFileSync(RC, "utf8"));
rc.codepoints = Object.fromEntries(
  names.map((name) => [name, rc.codepoints[name] ?? generated[name]]),
);
write(RC, rc);

const manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
manifest.contributes.icons = Object.fromEntries(
  names.map((name) => [
    `mindful-stage-${name}`,
    {
      description: `Mindful Stage ${name} icon`,
      default: {
        fontPath: "assets/mindful-stage.woff",
        fontCharacter: `\\${rc.codepoints[name].toString(16).toUpperCase()}`,
      },
    },
  ]),
);
write(MANIFEST, manifest);

const pascal = (name) =>
  name
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

writeFileSync(
  ICONS_TS,
  `// Generated by \`just icons\` from assets/icons. Re-run to re-generate. Do not edit directly.\n\nexport enum Icon {\n${names
    .map((name) => `  ${pascal(name)} = "mindful-stage-${name}",`)
    .join("\n")}\n}\n`,
);

console.log(`synced ${names.length} icons: ${names.join(", ")}`);
