// Generated by `just icons` from assets/icons. Re-run to re-generate. Do not edit directly.

export enum Icon {
  Clean = "mindful-stage-clean",
  MissingUpstream = "mindful-stage-missing-upstream",
  Ms = "mindful-stage-ms",
  Ready = "mindful-stage-ready",
  Unpushed = "mindful-stage-unpushed",
}
